name: test api
on: [push]
run-name: "Validate API by ${{ github.actor }}"

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: check Java versions
        run: java -version
      - name: run test
        run: mvn test verify
      - name: check status step
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"









